dist: trusty

language: python

cache:
  directories:
  - /home/travis/download
  - /home/travis/.cache/pip

matrix:
  fast_finish: true
  include:
    - env: PYTHON_VERSION="3.6" COVERAGE="true"
      sudo: required

notifications:
  email: false

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
